- hosts: localhost
  connection: local
  gather_facts: False

  roles:
    - build-vpc
    - build-sec-groups
    - build-instances

  tasks:
    - debug: var=vpc_id

- hosts: frontend:services:mysql:rabbitmq
  become: true
  roles:
    - hosts
